### ISSUE TITLE
Import pixelcnn++ to lucid

### ISSUE THREAD

**Issue by rtaori** [tensorflow/lucid#166]
Hi,

I'm trying to import Pixelcnn++ (https://github.com/openai/pixel-cnn) into Lucid, specifically the pretrained cifar10 version. I've tried using both the current API and the experimental one documented in #152 - in either case, I'm able to save the frozen graph successfully and load it into lucid (after changing batch size to 1 and naming the input and output nodes). However, when I then call `render_vis` or any related method, in both cases I get some weird shape errors:

```
Traceback (most recent call last):
  File "visualize.py", line 10, in <module>
    _ = render.render_vis(model, 'model_1/concat_197:0', param_f = lambda: param.image(32) * 2 - 1)
  File "/data/rohan/pixel-cnn/lucid/optvis/render.py", line 102, in render_vis
    loss_, _ = sess.run([loss, vis_op])
  File "/data/rohan/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/data/rohan/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/data/rohan/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/data/rohan/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,44,44,3] vs. shape[1] = [1,32,32,1]
	 [[node import/model_1/concat (defined at /data/rohan/pixel-cnn/lucid/modelzoo/vision_base.py:184) ]]
	 [[node Mean (defined at /data/rohan/pixel-cnn/lucid/optvis/objectives.py:168) ]]

Caused by op 'import/model_1/concat', defined at:
  File "visualize.py", line 10, in <module>
    _ = render.render_vis(model, 'model_1/concat_197:0', param_f = lambda: param.image(32) * 2 - 1)
  File "/data/rohan/pixel-cnn/lucid/optvis/render.py", line 94, in render_vis
    relu_gradient_override)
  File "/data/rohan/pixel-cnn/lucid/optvis/render.py", line 176, in make_vis_T
    T = import_model(model, transform_f(t_image), t_image)
  File "/data/rohan/pixel-cnn/lucid/optvis/render.py", line 256, in import_model
    model.import_graph(t_image, scope=scope, forget_xy_shape=True)
  File "/data/rohan/pixel-cnn/lucid/modelzoo/vision_base.py", line 184, in import_graph
    self.graph_def, {self.input_name: t_prep_input}, name=scope)
  File "/data/rohan/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/data/rohan/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/data/rohan/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 235, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/data/rohan/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3433, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/data/rohan/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3433, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/data/rohan/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3325, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/data/rohan/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): ConcatOp : Dimensions of inputs should match: shape[0] = [1,44,44,3] vs. shape[1] = [1,32,32,1]
	 [[node import/model_1/concat (defined at /data/rohan/pixel-cnn/lucid/modelzoo/vision_base.py:184) ]]
	 [[node Mean (defined at /data/rohan/pixel-cnn/lucid/optvis/objectives.py:168) ]]
```
I'm not sure why this happens and why one shape is 44x44 when this is a cifar10 model. I also made sure to pass in the right `param_f = lambda: param.image(32) * 2 - 1` which I think should pass in the required 32x32x3 input. Any advice would be appreciated, thanks!

**Comment by colah** [comment]
Hello! Yes,  `param_f = lambda: param.image(32) * 2 - 1` should produce a 32x32 parameterization. Those error messages seem to suggest the model wants a 44x44 input. Unfortunately, I'd need to start digging into your model to debug.

(FYI, I'd recommend changing the model definition value range to `[-1,1]` instead of transforming your parametrization with `2x-1` yourself. All our code assumes we know the correct input range.)

**Comment by rtaori** [comment]
I see. Yeah, not sure why that's the error message. The input is definitely 32x32 since it was trained on cifar. Thanks for the suggestion

**Comment by ludwigschubert** [comment]
@rtaori you may be seeing the result of our set of standard transforms. Can you try passing an empty list of transforms (`transforms=[]`) to any `render_` methods? I should probably switch to default to no transforms, or at least automatically crop to shape.

**Comment by rtaori** [comment]
Yes, that worked. Thank you!
